[package]
name = "discord-channel-archiver"
version = "0.3.0"
authors = ["Jamie Quigley <jamie@quigley.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
futures = "0.3.19"
gh-emoji = "1.0.6"
regex = "1.5.4"
reqwest = "0.11.8"
serde = "1.0.133"
serde_json = "1.0"
clap = { version = "3.0.0", features = ["derive"] }
text_io = "0.1.9"
tokio = {version = "1.15", features = ["macros", "rt-multi-thread"]}
once_cell = "1.9.0"
liquid = "0.23.1"
thiserror = "1.0.30"
tracing = "0.1.29"
tracing-subscriber = "0.3.5"

[dependencies.serenity]
default-features=false
features=["client", "gateway", "rustls_backend", "model", "cache", "unstable_discord_api"]
version = "0.10.9"

[profile.release]
debug = true

