[package]
name = "discord-channel-archiver"
version = "0.4.0"
authors = ["Jamie Quigley <jamie@quigley.xyz>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
futures = "0.3.21"
regex = "1.5.4"
reqwest = "0.11.9"
serde = "1.0.136"
serde_json = "1.0"
clap = { version = "3.0.14", features = ["derive"] }
tokio = {version = "1.16", features = ["macros", "rt-multi-thread"]}
once_cell = "1.9.0"
liquid = "0.23.1"
thiserror = "1.0.30"
tracing = "0.1.34"
tracing-subscriber = "0.3.8"

[dependencies.serenity]
default-features=false
features=["client", "gateway", "rustls_backend", "model", "cache", "unstable_discord_api"]
version = "0.10.10"

[profile.release]
debug = true

