[package]
name = "discord-channel-archiver"
version = "0.4.0"
authors = ["Jamie Quigley <jamie@quigley.xyz>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
futures = "0.3.21"
regex = "1.5.5"
reqwest = "0.11.10"
serde = "1.0.137"
serde_json = "1.0.81"
clap = { version = "3.1.17", features = ["derive"] }
tokio = {version = "1.18.1", features = ["macros", "rt-multi-thread"]}
once_cell = "1.10.0"
liquid = "0.26.0"
thiserror = "1.0.31"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"

[dependencies.serenity]
default-features=false
features=["client", "gateway", "rustls_backend", "model", "cache", "unstable_discord_api"]
version = "0.11.1"

[profile.release]
debug = true

