[package]
name = "discord-channel-archiver"
version = "0.3.0"
authors = ["Jamie Quigley <jamie@quigley.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
futures = "0.3.13"
gh-emoji = "1.0.6"
regex = "1.4.3"
reqwest = "0.11.2"
serde = "1.0.130"
serde_json = "1.0"
structopt = "0.3"
text_io = "0.1.8"
tokio = {version = "1.0", features = ["macros", "rt-multi-thread"]}
once_cell = "1.8.0"
liquid = "0.22.0"
thiserror = "1.0.25"
tracing = "0.1.27"
tracing-subscriber = "0.2.22"

[dependencies.serenity]
default-features=false
features=["client", "gateway", "rustls_backend", "model", "cache", "unstable_discord_api"]
version = "0.10.9"

[profile.release]
debug = true

