[package]
name = "discord-channel-archiver"
version = "0.3.0"
authors = ["Jamie Quigley <jamie@quigley.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
futures = "0.3.18"
gh-emoji = "1.0.6"
regex = "1.5.4"
reqwest = "0.11.7"
serde = "1.0.130"
serde_json = "1.0"
structopt = "0.3"
text_io = "0.1.9"
tokio = {version = "1.14", features = ["macros", "rt-multi-thread"]}
once_cell = "1.8.0"
liquid = "0.23.0"
thiserror = "1.0.30"
tracing = "0.1.29"
tracing-subscriber = "0.3.3"

[dependencies.serenity]
default-features=false
features=["client", "gateway", "rustls_backend", "model", "cache", "unstable_discord_api"]
version = "0.10.9"

[profile.release]
debug = true

