[package]
name = "discord-channel-archiver"
version = "0.1.0"
authors = ["Jamie Quigley <jamie@quigley.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
log = "0.4.11"
pretty_env_logger = "0.4.0"
reqwest = "0.10.10"
serde = "1.0.120"
serde_json = "1.0"
structopt = "0.3"
tokio = {version = "1.0", features = ["macros", "rt-multi-thread"]}

[dependencies.serenity]
default-features=false
features=["client", "gateway", "rustls_backend", "model", "cache"]
version = "0.10.2"
